services:
  - type: web
    name: todo
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password

  - type: web
    name: todo-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://todo-backend.onrender.com/api

databases:
  - name: todo-db
    plan: free
